# Generated by Django 5.1.4 on 2024-12-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_cancellation_reason_order_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
