# Generated by Django 5.1.4 on 2024-12-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivery_agent_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
